"""added at & updated at for orders model

Revision ID: a110d19cd3f5
Revises: fb01999a5a6a
Create Date: 2025-01-18 18:56:56.358873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a110d19cd3f5'
down_revision = 'fb01999a5a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_updated', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('date_updated')
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
