"""Modified Tables

Revision ID: fb01999a5a6a
Revises: 1346026ea458
Create Date: 2025-01-14 18:08:30.539054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb01999a5a6a'
down_revision = '1346026ea458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('delivered_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('img_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('img_path')
        batch_op.drop_column('source')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('delivered_date')
        batch_op.drop_column('purchase_date')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
